### Post User Register
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "username": "Arufiand",
  "password": "Abcd1234!",
  "name": "Arufiand"
}

###

### Post User Login
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "username": "Arufiand",
  "password": "Abcd1234!"
}

> {%
    client.global.set("auth_token", response.body.token);
%}

###

### Post User Register
PUT http://localhost:3001/api/users/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "username": "Arufiand",
  "password": "Abcd1234!",
  "name": "Arufian Danunuyu"
}

###

### GET All Routes
GET localhost:3001/api/routes

###
